version: '3.8'

services:

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    ports:
      - "5000:5000"
    env_file:
      - ./users-service/.env
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - users-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge